export const DRAWING_DISCIPLINES_TYPE_MAP: Record<string, string> = {
  G: 'General',
  C: 'Civil',
  L: 'Landscape',
  A: 'Architectural',
  GS: 'Signage',
  CS: 'Sunshade',
  S: 'Structural',
  M: 'Mechanical',
  P: 'Plumbing',
  FP: 'Fire Protection',
  E: 'Electrical',
  FA: 'Fire Alarm',
  TE: 'Telecommunications',
  AV: 'Audio/Video',
  SM: 'Sound Masking',
  TY: 'Security',
  LV: 'Low Voltage',
  JT: 'Joint Trench',
  U: 'Utility',
  IR: 'Irrigation',
  FS: 'Fire Sprinkler',
  TWC: 'Two Way Communication',
  AC: 'Access Control',
  SEC: 'Security',
  TC: 'Telecommunications',
  T: 'Technology'
}
